name: .NET

on:
  push:
    paths-ignore: "**/README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [8.0.x, 9.0.x, 10.0.x]
        template: [ console, classlib ]
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    # Windows
    # - shell: cmd
    #   run: |
    #     cd /d "C:\Program Files\dotnet\shared\Microsoft.NETCore.App" &&^
    #     dir
        
    - run: |
        dotnet new list

    - run: |
        dotnet new ${{ matrix.template }} -o my-${{ matrix.template }}-app-dotnet-v${{ matrix.dotnet-version }} --language "C#" --verbosity diagnostic

  # -p:UseAppHost=false 
    - if: ${{ matrix.container == 'console' }}
      working-directory: my-${{ matrix.template }}-app-dotnet-v${{ matrix.dotnet-version }}
      run: |
        dotnet publish -c Release --runtime win-x64 -p:PublishSingleFile=true -p:SelfContained=true --self-contained --verbosity diagnostic
    
    - if: ${{ matrix.container != 'console' }}
      working-directory: my-${{ matrix.template }}-app-dotnet-v${{ matrix.dotnet-version }}
      run: |
        dotnet publish -c Release --runtime win-x64 -p:SelfContained=true --self-contained --verbosity diagnostic
        
    - uses: actions/upload-artifact@v4.6.0
      with:
        name: "my-${{ matrix.template }}-app-dotnet-v${{ matrix.dotnet-version }}"
        path: "my-${{ matrix.template }}-app-dotnet-v${{ matrix.dotnet-version }}"
      
